version: 0.0
os: linux

files:
  - source: /index.html
    destination: /var/www/html
    overwrite: yes

hooks:
  BeforeInstall:
    - location: scripts/changepermission.sh
      timeout: 3600
      runas: root
  ApplicationStart:
    - location: scripts/install_dependencies.sh
      timeout: 3600
  AfterInstall:
    - location: scripts/start_apache.sh
      timeout: 180
      runas: root
  ValidateService:
    - location: scripts/status_apache.sh
      timeout: 3600
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root    
